# 此工作流使用未经 GitHub 认证的操作。
# 它们由第三方提供，并受
# 单独的服务条款、隐私政策和支持
# 文档管理。

name: build-and-push-image

on:
  workflow_call:
    inputs:
      distro:
        description: 'base image of docker image'
        default: 'ubuntu'
        required: false
        type: string
      version:
        description: 'base image version of docker image'
        default: '18.04'
        required: false
        type: string
      REGISTRY:
        description: 'docker image registry'
        default: 'ghcr.io'
        required: false
        type: string
jobs:
  build-and-push-image:
    runs-on: ubuntu-18.04
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: fpm-${{ inputs.distro }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.6.0
        with:
          images: ${{ inputs.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
          tags: type=raw,value=${{ inputs.version }}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./${{ inputs.distro }}/${{ inputs.version }}/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: test
        run: docker images
      - run: docker run --rm ${{ steps.meta.outputs.tags }} fpm --version
